### ISSUE TITLE
Taking advantage of network capabilities to use multiple IP addresses

### ISSUE THREAD

**Issue by annevk** [WICG/nav-speculation#1]
This seems like an overly optimistic take of https://tools.ietf.org/html/rfc4941 which doesn't really help all that much as users would still have a consistent IPv6 address prefix most of the time. You really need the ISP to be in on the scheme somehow and do sharing of its addresses across all its customers.

**Comment by jeremyroman** [comment]
I don't mean to rely on RFC 4941 and I admit I'm not a domain expert on IPv6. My understanding is that all the ISP would need to do is to give a sufficient number of customers the same v6 address prefix and allow the collision resolution algorithm to prevent multiple customers from using the same address at once. I've heard various opinions on whether ISPs would consider it in their interest to configure their IPv6 deployment in this way in the future, and I haven't consulted ISPs.

My purpose in mentioning wasn't to say that this would necessarily be available on all or most networks, just to use it as an example of a way of sending a request from a different source IP address that might be available to some users on some networks, which user agents could take advantage of to enhance those users' privacy.

I'm happy to clarify this if you can suggest better wording, but I really only intended to mention it in passing, in a parenthetical, to explain by way of example what I mean by "obscuring the source IP".
