### ISSUE TITLE
BroadcastChannel restrictions

### ISSUE THREAD

**Issue by noamr** [WICG/nav-speculation#141]
`BroadcastChannel` is used for same-origin messaging. By allowing it in prerendering contexts, it can lead to unintended/nonsensical behaviors. For example, one of the use-cases for `BroadcastChannel` is to notify a tab about sign-ins in other tabs. Making that notification when the page is not active yet feels counterintuitive.

Suggesting to do one of the following:

1. Buffer outgoing messages but allow incoming messages
2. Buffer outgoing and incoming messages
3. Delay creation without buffering (only messages received after activation will be received)

I'm in favor of (1) - it allows pages that require `BroadcastChannel` for their functionality to operate, while not creating side-effects on other contexts.

See [ITS discussion](https://groups.google.com/a/chromium.org/g/blink-dev/c/ogegRwcRlcs)

WIP PR:
https://github.com/WICG/nav-speculation/pull/140

**Comment by noamr** [comment]
@domenic @nyaxt @nhiroki @jeremyroman

**Comment by nyaxt** [comment]
Thanks! Let us investigate how we are doing in Chromium right now and report it back here.

**Comment by noamr** [comment]
> Thanks! Let us investigate how we are doing in Chromium right now and report it back here.

I am pretty sure BroadcastChannel doesn't have restrictions in chrome currently.

**Comment by noamr** [comment]
> `I am pretty sure BroadcastChannel doesn't have restrictions in chrome currently.`
> 
> We do not perform restrictions on it for now.
> 
> 
> 
> Thanks! There is some context that we decided to grant BraodcastChannel messages previously. 
> 
> At that time, prerender2 is triggered by a same-origin speculation rule, so we believe web developers who want to trigger prerendering should be aware of this API; active and prerendering pages can send and receive messages. So we decided to grant it. 
> 

Right. I guess omnibox pre-rendering can create more of an unexpected behavior.
> 
> 
> 1. Buffer outgoing messages but allow incoming messages
> 
> It sounds like we can make it possible. Maybe we can add `bc.postMessage` into the post-activation steps.?

Yes, that's basically what the PR does
> 
> 
> 
> 2. Buffer outgoing and incoming messages
> 
> Not sure for now... 
> 
> 
> 
> 3. Delay creation without buffering (only messages received after activation will be received)
> 
> `BroadcastChannel()` is a synchronous method, so we do not want to delay creation at that time. 
> 

I meant it more behaviorally, where the object is created but started receiving messages only post-activation

**Comment by nhiroki** [comment]
Implementation-wise, Chromium should be able to implement any options using the post-activation steps.

The option (1) seems sufficient for avoiding the scenario on the UA-initiated prerendering.

By the way, what about other cross-tab postMessage like `ServiceWorker#postMessage` and `ServiceWorkerClient#postMessage`? If we buffer outgoing message from a prerendered page, we may have to buffer `ServiceWorker#postMessage` in a prerendered page as well.

**Comment by noamr** [comment]
> Implementation-wise, Chromium should be able to implement any options using the post-activation steps.
> 
> The option (1) seems sufficient for avoiding the scenario on the UA-initiated prerendering.
> 
> By the way, what about other cross-tab postMessage like `ServiceWorker#postMessage` and `ServiceWorkerClient#postMessage`? If we buffer outgoing message from a prerendered page, we may have to buffer `ServiceWorker#postMessage` in a prerendered page as well.

That's a good point. I don't know where the right place is to draw the line - we can't hermetically seal side effects of prerendering contexts on active contexts, it's more of a best effort to prevent weird prerendering-initiated website bugs. My instinct says to either delay both `BroadcastChannel` and `ServiceWorker#postMessage` or neither but I'd love to hear more voices.

(`ServiceWorkerClient#postMessage` is done from the context of the service worker anyway, and service worker registration is delayed).

**Comment by domenic** [comment]
> For example, one of the use-cases for BroadcastChannel is to notify a tab about sign-ins in other tabs. Making that notification when the page is not active yet feels counterintuitive.

Eh? For that particular use case I think you'd want the prerendered tab to update itself, right? Otherwise, you force more special-case code in the `prerenderingchange` handler.

Now, on balance I think the concerns in #113 are more serious. But I want to make sure we're on the same page for this particular example. It seems intuitive, not counterintuitive, to allow such state updates.

> Suggesting to do one of the following:

I think I slightly favor (1). But (2) could also work.

(2) feels more consistent and easy to explain. But (1) allows the case we're discussing above to work "faster", e.g. the prerendered page could update for login state while it is being prerendered, instead of only after after activation. More generally, (1) lets more processing happen in the background, which improves perceived performance.

(2) could perhaps be loosened to (1) in the future, similar to how we currently suspend workers but could loosen them to run in the future. But there may be slight compat risks in such a change.

> (ServiceWorkerClient#postMessage is done from the context of the service worker anyway, and service worker registration is delayed).

Service worker registration is delayed, but if you already have a registered service worker it will run. This is an outstanding issue I pointed out in the last paragraph of https://github.com/WICG/nav-speculation/issues/44#issuecomment-1031700022 .

**Comment by noamr** [comment]
> > For example, one of the use-cases for BroadcastChannel is to notify a tab about sign-ins in other tabs. Making that notification when the page is not active yet feels counterintuitive.
> 
> Eh? For that particular use case I think you'd want the prerendered tab to update itself, right? Otherwise, you force more special-case code in the `prerenderingchange` handler.

Sorry, I meant:
- there is an active document, listening to a BroadcastChannel to see if other tabs log in to the same origin
- You start typing something in the URL bar
- The browser thinks you're going to open another tab of the same domain
- The active document gets a notification "we're seeing that you logged in at another tab. Switch the session or stay here?", before you pressed Enter.

**Comment by noamr** [comment]
I believe whatsapp uses `ServiceWorker.postMessage` for 

> > > For example, one of the use-cases for BroadcastChannel is to notify a tab about sign-ins in other tabs. Making that notification when the page is not active yet feels counterintuitive.
> > 
> > 
> > Eh? For that particular use case I think you'd want the prerendered tab to update itself, right? Otherwise, you force more special-case code in the `prerenderingchange` handler.
> 
> Sorry, I meant:
> 
> * there is an active document, listening to a BroadcastChannel to see if other tabs log in to the same origin
> * You start typing something in the URL bar
> * The browser thinks you're going to open another tab of the same origin, starts prerendering
> * The prerendered document from the same origin broadcasts that it's on
> * The active document gets a notification "we're seeing that you logged in at another tab. Switch the session or stay here?", before you pressed Enter.

I believe whatsapp uses `ServiceWorker.postMessage` for this purpose, which could create the same nonsensical behavior (you would get "Whatsapp is open in another tab" before you opened the new tab).

**Comment by noamr** [comment]
Note that this kind of unexpected behavior is only relevant to omnibox prerendering - if WhatsApp or the likes opts-in to `speculationrules` prerendering they might as well get full `BroadcastChannel` support and deal with it themselves. It's also only relevant when there are live pages of the same origin.

I think an alternative way which might be the safest way to prevent this kind of nonsensical behavior is to prevent omnibox prerendering if there is an existing live page of the same origin. But would that cripple omnibox prerendering too much?

I think going forward it might be beneficial to be more precise about some of the restrictions to make some of them omnibox-only or document-initiated-only. See https://github.com/WICG/nav-speculation/issues/143

I suggest for now to defer all those APIs in favor of simplicity, and address the option to relax restrictions in certain scenarios later.

**Comment by jeremyroman** [comment]
To me it feels more natural to add an option to the `BroadcastChannel` constructor in the future (indicating that it should be fully on notwithstanding prerendering) than to create more divergent modes of prerendering, if authors need to turn it back on.
