### ISSUE TITLE
Is a prerendering page allowed to execute sendBeacon? 

### ISSUE THREAD

**Issue by Clqsin45** [WICG/nav-speculation#146]
Hello all, :-)
I'm wondering whether we want to allow prerendering pages to send a beacon ping? [1]
Would it cause information leak? Should we defer it until acitvation? 
If we'd like to defer it, shall we return true or false in this case?  

[1] https://w3c.github.io/beacon/#sendbeacon-method

**Comment by domenic** [comment]
I don't see any reason to restrict this; we don't restrict `fetch()`.

**Comment by Clqsin45** [comment]
I see. Thanks for the confirmation!
I raised this question when I saw some logging service relies on this API, and felt they may not know they are being prerendered. But this is not caused by this API.
