### ISSUE TITLE
Allow setting referrer policy in speculation rules

### ISSUE THREAD

**Issue by domenic** [WICG/nav-speculation#167]
We currently do not allow using a prerender or prefetch that has a mismatched referrer policy.

And, we always prerender or prefetch using the page's overall default referrer policy.

This means that if a site has something like this:

```html
<script type=speculationrules>
{
  "prerender": [{
    "source": "list",
    "urls": ["page.html"]
  }]
}
</script>
<a rel="noreferrer" href="page.html">click me</a>
```

then the prerender will be discarded instead of activated. This is correct behavior, but is unfortunate.

We could solve this with document rules. Or, we could allow setting the expected referrer policy in the list rules, e.g.

```json
{
  "prerender": [{
    "source": "list",
    "urls": ["page.html"],
    "referrer_policy": "no-referrer"
  }]
}
```

**Comment by domenic** [comment]
An alternative was discussed in https://github.com/WICG/nav-speculation/issues/18, which is removing the requirement of referrer policy matching. There, we decided the reason we kept it was mostly to help in some cross-site cases related to cookies. I wonder if we should consider revisiting that decision, at least for same-site cases?

In particular, @domfarolino's survey in https://github.com/WICG/nav-speculation/issues/18#issuecomment-759647076 of how nothing else keys on referrer policy is pretty convincing...

**Comment by domenic** [comment]
> An alternative was discussed in #18, which is removing the requirement of referrer policy matching.

This is not a full alternative, however. Consider a site which _does_ want to vary its content based on referrer. That site sends `Vary: referer`. Then, we really should require referrer matching.

For such sites, we need a way to indicate the referrer policy at prerendering time anyway. So, I think I am back to adding `"referrer_policy"` in the list rules.

**Comment by jeremyroman** [comment]
Agreed we want syntax for it at least for list rules; in my mind that was always going to happen, just a question of priority. Failing that we should respect the attribute on the link (for document rules) and the document's default referrer policy.

I need to give it more thought, but I think I'm coming around on not keying on referrer policy at least if `Vary: Referer` isn't present. The arguments about how caches work are at least somewhat convincing, and we'd already previously talked about enforcing a minimum referrer policy.

**Comment by toyoshim** [comment]
@domenic @jeremyroman hi, how is the status on this change? is there a specific blocker. or just isn't a high-priority item?
For a supportive input, I'm seeing a case that a major site hits this problem when I enforce the site to use prerendering.

**Comment by kjmcnee** [comment]
Implementation-wise I have a WIP CL here: https://chromium-review.googlesource.com/c/chromium/src/+/3971707 , which is almost ready for review.

**Comment by kjmcnee** [comment]
We've now spec'd the "referrer_policy" key in speculation rules. I'll go ahead and close this.
