### ISSUE TITLE
Prerendering and non-current target windows

### ISSUE THREAD

**Issue by domenic** [WICG/nav-speculation#168]
In the Chromium implementation, we have accidentally created an architecture where it is hard to prerender a page without knowing what target window (or tab) it is going to be in. Currently we are always assuming that the prerender will be navigated to in the current window. This means that in scenarios like

```html
<script type=speculationrules>
{
  "prerender": [{
    "source": "list",
    "urls": ["page.html"]
  }]
}
</script>
<a target="_blank" href="page.html">click me</a>
```

the prerender will be discarded instead of activated. Instead, we would like to allow such scenarios to be prerendered.

Ideally, we would do the implementation work to allow prerendering a page without knowing its target window ahead of time. That is important for supporting cases like the user middle-clicking on a prerendered link, where we just don't know until the user clicks where the page will be opened. However, this is estimated to be an extremely large (~year-plus) project. So we are interested in coming up with something usable in the meantime, for sites that want to benefit from prerendering but have a lot of links they know will often or always be opened in a new tab.

There are basically two options I can think of here:

- Extend speculation rules to allow specifying the target window. E.g. `"urls": [{ "url": "page.html", "target": "_blank" }]`.

  - We could instead locate the target specification outside the URL list, assuming it applies to multiple URLs at once: i.e. `{ "source": "list", "target": "_blank", "urls": ["page.html"] }`. This might play well with the proposed [scores](https://github.com/WICG/nav-speculation/blob/main/triggers.md#rules), e.g. if a page suspects or has telemetry that the user will open in the same tab most of the time but a new tab sometimes, they could do `[{ "source": "list", "target": "_self", "urls": ["page.html"], score: "0.8" }, { "source": "list", "target": "_blank", "urls": ["page.html"], "score": 0.2 }]`.

  - We make this into a hint, e.g. with the name `target_hint`, instead of a constraint. Then in the future if Chromium no longer has the same architectural constraint, we could use the prerender regardless of the `target_hint` value.

  - We could deprecate and remove this over time (especially the hint variant) if Chromium manages to overhaul the architecture enough to support being agnostic.

  - Here I've envisioned a general target specification, which allows any [valid browsing context name or keyword](https://html.spec.whatwg.org/#valid-browsing-context-name-or-keyword). That feels most webby. However it's not clear we'd want to support the additional complexity beyond `_self` and `_blank`, e.g. `_parent`/`_top` don't make a lot of difference because we currently only implement prerendering of top-level browsing contexts, and names targeting other preexisting windows might be extra work to implement. (Or, it might be very useful, for certain sites??)

- Heuristics. E.g. in the scenario above, notice that there is one link to `page.html` in the document, and it has `target="_blank"`.

  - This pairs especially well with document rules, and indeed we will probably need to implement something like this anyway if/when we do document rules.

  - In theory the heuristics here could be complex, e.g. some local statistical database of `(referrer, destination) -> target window` URL pairs based on past user activity on that site. In practice it seems unlikely building such infrastructure would be worthwhile.

  - This doesn't work well for pages that do new-tab navigations via things like `<button onclick="window.open(url)">`. They would have to add a fake link to trigger the heuristic.

  - This doesn't work great for pages that have a mix of some-new-tab, some-same-tab navigations to the same destination. (But, such sites seem rare?)

  - This is a bit more costly performance wise, as we need to scan the document whenever speculation rules were updated to determine the appropriate targets.

**Comment by domenic** [comment]
My tentative preference: `"target_hint"` outside the URL list. So we'd have

```json
{
  "prerender": [{
    "source": "list",
    "urls": ["page.html"],
    "target_hint": "_blank"
  }]
}
```

**Comment by nhiroki** [comment]
+1 to `target_hint` outside the URL list.

With this approach, I imagine that a [prerendering browsing contexts map](https://wicg.github.io/nav-speculation/prerendering.html#document-prerendering-browsing-contexts-map) would be an ordered map of (URL, referrer policy, target hint) tuples to prerendering browsing contexts. Then, the "[can activate a prerender](https://wicg.github.io/nav-speculation/prerendering.html#can-activate-a-prerender)" algorithm would check if the tuple matches those of the request.

**Comment by jeremyroman** [comment]
Is there a reason, aside from Chromium implementation constraints, to restrict on the target hint? If not, we probably shouldn't spec that UAs must restrict on it.

Otherwise, I think this makes sense. For document rules we can look at the actual `target` attribute (at least by default) on the link, but for list rules an indication here makes sense.

It's less clear to me what we'd do for a hint that named a window. Is that a useful/sensible thing to do, especially since which window that name refers to can change?

**Comment by domenic** [comment]
+1 to not restricting on it.

A hint that named a window seems potentially useful, albeit I would only want to implement it (as opposed to allowing it but ignoring it) if the implementation came for free. Consider a  slide show window plus a controller window, where the controller window controls the slide show window via named window targeting. As you hover over the "next slide" button, it could trigger a prerender targeted at the slide show window. This wouldn't be possible if we only allowed `_blank` targeting.

And yes, window name targets can change over time; but I think just treating that as an edge case, where if you change the name between prerendering and activation you don't get the benefits, is OK.

**Comment by domenic** [comment]
@KenjiBaheux points out offline that you might want to get a prerender that works regardless of the possible targets. I think that would be captured via multiple speculation rules blocks:

```html
<script type=speculationrules>
{
  "prerender": [{
    "source": "list",
    "urls": ["page.html"]
  }],
  "prerender": [{
    "source": "list",
    "urls": ["page.html"],
    "target_hint": "_blank"
  }]
}
</script>
<a href="page.html">click me</a>
<a target="_blank" href="page.html">click me also!</a>
```

(you could add an explicit `"target_hint": "_self"` to the first if you wanted.)

In a future user agent where the hint is not necessary, this would be harmlessly redundant.

We could consider making this easier, e.g. with `"target_hints": ["_self", "_blank"]`, but I think that might be a bit too easy to use, at least in current implementations (Chromium) where that will double your resource usage.

He similarly asks about cases where different links have different targets. Indeed, this seems like another candidate for multiple speculation rules blocks:

```html
<script type=speculationrules>
{
  "prerender": [{
    "source": "list",
    "urls": ["page.html"]
  }],
  "prerender": [{
    "source": "list",
    "urls": ["page2.html"],
    "target_hint": "_blank"
  }]
}
</script>
<a href="page.html">click me</a>
<a target="_blank" href="page2.html">click me also!</a>
```

**Comment by jeremyroman** [comment]
+1; that's exactly what I would have imagined. With document rules we can implicitly use the `target` attribute which would be even more natural.
