### ISSUE TITLE
Consider removing "source" from speculation rules objects

### ISSUE THREAD

**Issue by domenic** [WICG/nav-speculation#169]
For ergonomics, it would be simpler to be able to write `{ "urls": [...] }` instead of `{ "source": "list", "urls": [...] }`.

This would only work if we think every future list source will have distinct, distinguishable keys which we could use to infer the source. So far, for all cases in the explainer, this is the case: none of the document-source rules use `"urls"`. (And I believe the opposite also holds, where none of the keys that are unique to document rules can be used in list rules.)

It's a bit constraining, but I think the ergonomic benefits would be substantial.

**Comment by jeremyroman** [comment]
If we made this change, would we:
- ignore `"source"`
- make `"source"` optional but validated if present
- make rules which specify `"source"` illegal (a breaking change)

I don't have any concerns for anything I have immediately planned, aside from (1) it's a bit magical, and (2) it might constrain future evolution. I do agree that it scans a little more nicely, though.

**Comment by domenic** [comment]
Good question. I was thinking we would ignore `"source"`, but I realize now that conflicts with the general strategy of making rules that specify unknown keys illegal. So I don't have any strong preference between those, except that the compat pain of making it immediately illegal is probably not worth it. (And it's questionable whether the early-adopter pain of making it eventually-illegal would be worthwhile.)

If I had to pick one, I'd say ignore `"source"`, with a note in the spec saying that in earlier versions it was useful but now it's no longer used. I could see that happening again in the future with some other key, e.g. `"target_hint"`, so it's probably fine to accept.
