### ISSUE TITLE
What exactly are we trying to achieve with keying off of referrer policy?

### ISSUE THREAD

**Issue by domfarolino** [WICG/nav-speculation#18]
While reviewing some internal threads, and @domenic [Prerendering activation matching](https://docs.google.com/document/d/1E82ZqXibjCvpPdOgMmOfPIatPMEBVAiJ2KQm6r1_E94/edit) doc (+ the discussion on it), I was trying to think of what exactly keying off of the referrer policy buys us.

I initially thought that it was to capture the fact that requests sent with different referrer policies from the same document will be sent with different `Referer`s, and thus could yield different responses from the server [1], so we shouldn't activate the same prerendered browsing context for both of these requests. In other words, we're using the referrer policy as a rough proxy for what the `Referer` would be, which then slightly intersects with `Vary: Referer` behavior. Furthermore, I thought it might buy us consistency with the value of document.referrer on the prerendered document. All of this assumes that two requests with the same referrer policy coming from the same document will be sent with the same `Referer` header though.

I then realized that it's pretty easy to send two requests from the same document that ultimately have the same referrer policy, but different `Referer`s if you use redirects. For example:
 1. A.com prerenders B.com {referrer policy: origin, `Referer: A.com`}
 1. A.com navigates to D.com/ToB {referrer policy: no-referrer, /no referrer/}
    - D.com redirects to B.com, attempting to activate the prerender
    - The redirect sets the referrer policy to `origin` to match the prerender
    - The request for B.com looks like {referrer policy: origin, /no referrer/}, and matches the prerender given our referrer policy criteria

This results in a successful prerender activation. Both the prerender and activation requests have the same referrer policy, but entirely different `Referer`s (in fact one was sent without this header altogether). This might not be a big deal, especially since it's an edge case, but I felt it was worth pointing out.

I guess the alternative would be to key off of the computed `Referer`, but that's basically the same as if ever prerender response had `Vary: Referer` (and we honored it in our activation logic), which seems pretty unlikely.

Keying off of the referrer policy just felt a little strange given the case I mentioned, and the fact that it seems to be acting as a pseudo-proxy for the `Referer` header I guess. I'm fine with it, but I just want to make sure I understand the intent fully.

[1]: This is the argument we made when trying to partition HTML's "list of available images" cache on the referrer policy as well, for consistency with other properties if nothing else

**Comment by domenic** [comment]
The intent, which was done mostly based on pattern-matching and not deep thinking, was this: given

```html
<a href="https://example.org/" referrerpolicy="no-referrer">Click me</a>
```

then normally clicking on that `<a>` will deliver no `Referer` to `https://example.org/`. That is, the page has made it very clear that they expect that following that `<a>` will not leak information about the referrer to `example.org`, and the browser will enforce that.

Now consider

```html
<link rel="prerender2" referrerpolicy="unsafe-url" href="https://example.org/">
<a href="https://example.org/" referrerpolicy="no-referrer">Click me</a>
```

Adding this `<link>` should not break the page's anti-leaking protection.

---

Writing this out, the reasoning doesn't seem super-sound. The page is, after all, doing this to itself.

And, the referrer has already "leaked" by the time the link is clicked: it leaked when the prerendering happened. So what does preventing the match really gain us?

Clicking on the `<a>` _does_ give the prerendered page storage access, which might make this interesting. But I don't think that changes much. RP-keying can't be part of our privacy protections, because if it were, then it'd be easily defeated by just changing the `<a>` to use `referrerpolicy="unsafe-url"`. We may separately need privacy protections to lock down the referrer when prerendering (I think I recall an internal thread about that?), but I don't think RP-keying plays a role there.

---

So, all I'm left with is a vague sense that "things should match". But I don't think it buys us anything concrete. So yeah, I'm inclined to remove this keying.

It'd be kind of nice to be consistent, though, across all such "memory caches": e.g., the list of available images, the general memory cache, and the prerendering browsing context map. Do you have thoughts on that?

**Comment by domfarolino** [comment]
Your analysis makes good sense to me.

I also do feel like "things should match" as a general principle is good. From taking a look around and doing some excavation I've determined the following:

- Blink's [preload cache matching logic](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/loader/fetch/resource_fetcher.cc;l=1343;drc=7ccffaf0933ccc647c744bf66971bcf5f33a676a) does not key on the referrer policy
- Blink's general [memory cache matching logic](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/loader/fetch/resource_fetcher.cc;l=1526;drc=7ccffaf0933ccc647c744bf66971bcf5f33a676a) does not key on the referrer policy
- Blink's general [Resource reuse matching logic](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/loader/fetch/resource.cc;l=732;drc=7ccffaf0933ccc647c744bf66971bcf5f33a676a) does not key on the referrer policy
    - This is just some specific logic that also happens to be used by preload and general memory cache matching logic
 - The HTML Standard's [list of available images](https://html.spec.whatwg.org/multipage/images.html#the-list-of-available-images) is not keyed on the referrer policy, despite my efforts in trying to make this happen (https://github.com/whatwg/html/issues/5541)
 - Consequently, Blink's [list of available images matching logic](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/loader/image_loader.cc;l=92-116;drc=2abcb8819929c8dd18451e27723934b470d98bf4) that I added last year also does not key on the referrer policy, despite `referrerpolicy` attribute mutations being considered "relevant"

With all of that, when the day comes when we do standardize the Memory Cache + Preload Cache, I think it will not key on referrer policy unless something new comes up, so I am also inclined to remove this matching logic. I'll go ahead and own this issue and take care of that.

**Comment by jeremyroman** [comment]
> The intent, which was done mostly based on pattern-matching and not deep thinking, was this: given
> 
> ```
> <a href="https://example.org/" referrerpolicy="no-referrer">Click me</a>
> ```
> 
> then normally clicking on that `<a>` will deliver no `Referer` to `https://example.org/`. That is, the page has made it very clear that they expect that following that `<a>` will not leak information about the referrer to `example.org`, and the browser will enforce that.
> 
> Now consider
> 
> ```
> <link rel="prerender2" referrerpolicy="unsafe-url" href="https://example.org/">
> <a href="https://example.org/" referrerpolicy="no-referrer">Click me</a>
> ```
> 
> Adding this `<link>` should not break the page's anti-leaking protection.
> 
> Writing this out, the reasoning doesn't seem super-sound. The page is, after all, doing this to itself.
> 
> And, the referrer has already "leaked" by the time the link is clicked: it leaked when the prerendering happened. So what does preventing the match really gain us?

The association between the referrer and the site's first-party cookies has not leaked at that point, though. Contrived example:

```
<link rel=prerender href="https://shopping.example/cool-new-product" referrerpolicy="origin">

...and that's my review of why you should definitely but the Cool New Product!

<!-- we expect this link to usually be clicked, so we ask for it to be prerendered,
     and the origin is used to tag a session for affiliate credit -->
If you wanna buy it,
<a href="https://shopping.example/cool-new-product" referrerpolicy="origin">use this link</a>
so they know I sent you.

If you're worried about tracking, I understand that, go ahead and use
<a href="https://shopping.example/cool-new-product" referrerpolicy="no-referrer">this link instead</a>.
```

> Clicking on the `<a>` _does_ give the prerendered page storage access, which might make this interesting. But I don't think that changes much. RP-keying can't be part of our privacy protections, because if it were, then it'd be easily defeated by just changing the `<a>` to use `referrerpolicy="unsafe-url"`. We may separately need privacy protections to lock down the referrer when prerendering (I think I recall an internal thread about that?), but I don't think RP-keying plays a role there.

I don't think it affects the UA's protections against coordinating parties. And as you say, the site did technically do it to itself, but I think it's still mildly surprising (if a bit of an edge case).

> So, all I'm left with is a vague sense that "things should match". But I don't think it buys us anything concrete. So yeah, I'm inclined to remove this keying.
> 
> It'd be kind of nice to be consistent, though, across all such "memory caches": e.g., the list of available images, the general memory cache, and the prerendering browsing context map. Do you have thoughts on that?

**Comment by domfarolino** [comment]
We discussed this more in another meeting, and I think we're slightly leaning towards keeping the keying as-is (though personally I am slightly leaning towards not keying on the referrer policy). This deviates from other caches in the web platform, but I think it is reasonable because with those other caches, the only thing we miss out on by not keying on referrer policy is some albeit incomplete protection against `Vary: Referer`. Whereas with prerendering, you could argue that we're trying to protect the user from activating a prerendered resource whose `Referer` was different than the activation navigation; this resource could later join the "unintentionally-leaked" referrer information with first party cookies when the prerender is activated, which is kind of a foot gun. This is demonstrated in Jeremy's example above, and mitigating this improves general correctness at the cost of a little extra work and slight deviation from some other caches on the platform.

Given that, I'll close this issue for now.

**Comment by domenic** [comment]
Let's reopen to disentangle this discussion from https://github.com/WICG/nav-speculation/issues/167. I'm also going to assume https://github.com/WICG/nav-speculation/issues/170 is accepted.

I think we now have a couple options on the table:

1. Don't key on referrer policy.

1. Key on referrer policy.

1. Key on referrer policy for cross-site, but don't key for same-site.

(3) is a bit icky. Can we do (1), or do the concerns in https://github.com/WICG/nav-speculation/issues/18#issuecomment-759703856 prohibit it? Note that we [already require](https://wicg.github.io/nav-speculation/prefetch.html#list-of-sufficiently-strict-speculative-navigation-referrer-policies) avoiding "origin", "no-referrer-when-downgrade", "origin-when-cross-origin", and "unsafe-url".

**Comment by jeremyroman** [comment]
I don't think those concerns are critical, because of the reason you mentioned plus the fact that authors can always not request prefetch/prerender in such cases, or request it with the more restrictive referrer policy.
