### ISSUE TITLE
Add specification for Web Locks API

### ISSUE THREAD

**Issue by Clqsin45** [WICG/nav-speculation#185]
Requesting a web lock returns a promise, so this API seems can be deferred. 
We may want to describe the expected behavior.

**Comment by Clqsin45** [comment]
(filed this issue because I am reviewing a CL that upstreams the tests for Web Locks. happy to update the specification for it 
:-))

**Comment by domenic** [comment]
Happy to review such an update! It seems like it might very similar to other simple cases like https://wicg.github.io/nav-speculation/prerendering.html#webhid-patch .

**Comment by Clqsin45** [comment]
Thanks for the link! I add a new section to the specification and uploaded the patch.
