### ISSUE TITLE
Incorrect-looking header syntax in no-vary-search explainer

### ISSUE THREAD

**Issue by ricea** [WICG/nav-speculation#199]
> For example, consider the [previous underwater phone article example](https://github.com/WICG/nav-speculation/blob/main/no-vary-search.md#carrying-data-not-yet-determined-at-the-time-of-preloading), assuming that /articles/new-underwater-phone responds with `No-Vary-Search: "via"`.

`No-Vary-Search: "via"` doesn't seem to match the syntax used elsewhere in the document.

**Comment by domenic** [comment]
Fixed in https://github.com/WICG/nav-speculation/commit/092f71bd594334f4c597c601fbb5e69f9873eb10, but I forgot to reference the issue in the commit message... that's what I get for pushing directly to main. Ah well.
