### ISSUE TITLE
Fill out fetch.md with cross-origin prerendering fetch requirements

### ISSUE THREAD

**Issue by domfarolino** [WICG/nav-speculation#20]
I've been working on explainer-izing our requirements for fetching specifically cross-origin prerender requests, and https://github.com/jeremyroman/alternate-loading-modes/blob/main/fetch.md seems like the right place to put this when I'm done, so I'm filing this as a tracking bug and will submit a PR when what I have locally is more complete.

Right now I'm mostly considering:
 1. HTTP Cache mechanics
 1. Requirements on credentials
 1. Referrer information that we'll send

... and describing which of the above will need to trickle down to affect subresources, and subresources in nested browsing contexts. I _think_ same-origin prerenders don't really need to do anything special in the above areas, but I'll need to double check.

----

A concrete spec design for all of these will come shortly after!

**Comment by jeremyroman** [comment]
The `Purpose` header or equivalent should probably also be in there. It might also be useful to call out connection pools here (maybe non-normatively as far as spec text goes, if we don't ordinarily spec connection pooling).

**Comment by domfarolino** [comment]
All three of the fetch restrictions in the OP are explainerized. I agree we need to explain and spec [`Sec-Purpose: prefetch`](https://www.chromestatus.com/feature/6247959677108224). I don't think we need to do anything special with connection pools, since each [connection in the Fetch spec](https://fetch.spec.whatwg.org/#connections) is keyed off of the network partition key, and I believe we'll be using a "speculative" partition key for a particular origin for speculative navigation requests.
