### ISSUE TITLE
No-Vary-Search canonicalization behavior

### ISSUE THREAD

**Issue by domenic** [WICG/nav-speculation#201]
No-Vary-Search does not have a processing model for actually matching cache keys specified yet.

However, our plan is to base the processing model on [the application/x-www-form-urlencoded parser](https://url.spec.whatwg.org/#urlencoded-parsing).

This leads to some interesting behavior, because even if two strings are exact matches in terms of parsed search params, they may not be exact string matches. For example, `/foo?bar=baz&&&&` and `/foo?bar=baz` both have the same parsed search params.

The question is, when do these start matching?

- Does `No-Vary-Search: params=?0, key-order=?0`, which looks like it should have no effect, actually cause that new non-default behavior to occur?

- Do we decide to start doing this only after `params` becomes nonempty, or `key-order` gets set to true?

- Other ideas?

**Comment by jeremyroman** [comment]
The second option seems best to me, even though it's slightly awkward. The presence of anything that would permit us to modify the search params by adding/removing/reordering parameters opens up the possibility of doing so in a way that affects such things.
