### ISSUE TITLE
Remove [DelayWhilePrerendering] in Screen Capture API

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/nav-speculation#225]
The `getDisplayMedia()` method in the Screen Capture API [requires transient user activation](https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia).
I believe this makes this API fit into the list of [implicitly restricted APIs](https://wicg.github.io/nav-speculation/prerendering.html#implicitly-restricted). Currently, it seems like the spec does not: https://wicg.github.io/nav-speculation/prerendering.html#screen-capture-patch

**Comment by domenic** [comment]
Thank you! Would you be interested in sending a PR?

**Comment by beaufortfrancois** [comment]
Sure. I'll do that Monday
