### ISSUE TITLE
Document rules should be limited to rendered links

### ISSUE THREAD

**Issue by jeremyroman** [WICG/nav-speculation#246]
see also https://chromium-review.googlesource.com/c/chromium/src/+/4226934

Users aren't likely to click on such links, and for selectors, Chromium's style engine (and likely others) avoid computing style for unrendered subtrees (due to display:none or shadow roots). So we should probably only consider links which are [being rendered](https://html.spec.whatwg.org/multipage/rendering.html#being-rendered).

cc @a4sriniv

**Comment by jeremyroman** [comment]
@a4sriniv Is display locking (content-visibility) covered by the "rendered" concept, or does it need separate spec wording?

**Comment by a4sriniv** [comment]
I think it needs separate spec wording. From https://drafts.csswg.org/css-contain/#content-visibility, "The [content-visibility](https://drafts.csswg.org/css-contain/#propdef-content-visibility) property controls whether or not an element renders its contents at all". But I don't think rendered here corresponds to "being rendered". 

The rest of the `content-visibility` spec uses the concept of [skipping an element's contents](https://drafts.csswg.org/css-contain/#skips-its-contents). In particular it says: "The user agent should additionally **_avoid as much layout/rendering work as possible_** for [skipped contents](https://drafts.csswg.org/css-contain/#skips-its-contents)", and also "If rendering work is done at some point, the user-agent should retain the previously computed layout state if possible, to allow the skipped contents to be displayed quickly at a later moment." The wording seems to indicate that this is a different state from explicitly not being rendered, and some rendering work may be done even if the contents aren't painted on screen.

Right now, the document rules implementation only omits links in the contents of a display-locked element if their style is not up-to-date, which isn't always the case for skipped contents (wording from spec,  "to a large extent do not update their styles at all unless explicitly requested by script"). But we could update the implementation to just omit links inside skipped contents all the time, and the behaviour could then be described as: "_document rules do not apply to links that are flat-tree descendants of elements with skipped contents_".

**Comment by jeremyroman** [comment]
I would prefer that this work in a way that will apply to other implementations if possible, rather than being contingent on when Blink (or another particular engine) calculates style. While we could say it _may_ not detect "skipped" links, it seems more consistent and predictable to specify that it always ignores them -- or alternatively, specify what the conditions actually are.

**Comment by a4sriniv** [comment]
LGTM, thank you!
