### ISSUE TITLE
Please rename No-Vary-Search to No-Vary-Query

### ISSUE THREAD

**Issue by ricea** [WICG/nav-speculation#249]
The name "search" is not widely used for the part after the `?` in a URL, except in JavaScript APIs.

At the HTTP-level "query" is used to describe the part after the `?` and not "search". Since it's an HTTP header, it should use HTTP semantics.

Even the URL standard calls it "query": https://url.spec.whatwg.org/#dom-url-search

**Comment by domenic** [comment]
We've gotten conflicting feedback on this. Other browser vendors (@annevk) noted that "query" is not exposed in any web platform API, but "search" was exposed multiple times on the web platform, and so suggested we stick with "search".

I don't have any strong preference here.

**Comment by domenic** [comment]
Modern Node.js uses the URL Standard API, including URLSearchParams. But yeah, if we were designing a feature for non-JavaScript server runtimes, we'd probably use query. We're not though; we're designing a web platform feature...

**Comment by jeremyroman** [comment]
In fact if you dig in the history, this was originally called `No-Vary-Query` which conditionally rhymed (depending on how you pronounce "query") and I preferred that, but when we talked about it (incl. at TPAC) the argument that web platform APIs say "search" and not "query" won the day.

**Comment by ricea** [comment]
Okay, I give up.
