### ISSUE TITLE
Recent HTTPS-skipping commit is not correct

### ISSUE THREAD

**Issue by domenic** [WICG/nav-speculation#255]
https://github.com/WICG/nav-speculation/commit/18a76e0601d028f01e5c1ac07e4d362d0c36ba70

|href| is a string, not a URL record, so it does not have a scheme.

You should instead look at the element's [url](https://html.spec.whatwg.org/#concept-hyperlink-url).

@a4sriniv

**Comment by a4sriniv** [comment]
Thanks! Out of curiosity, does "Let prerenderCandidate be a new [prerender candidate](https://github.com/WICG/nav-speculation/issues/255#prerender-candidate) whose [URL](https://github.com/WICG/nav-speculation/issues/255#prerender-candidate-url) is href" work or is that a bug too?

**Comment by jeremyroman** [comment]
I think that's also a bug. As @domenic pointed out, href currently returns a USVString (the serialization of the URL), not the [URL record](https://url.spec.whatwg.org/#concept-url).
