### ISSUE TITLE
Priority/Order of pre-renders

### ISSUE THREAD

**Issue by thinklinux** [WICG/nav-speculation#288]
As far as I can see in the application tab in dev tools, urls are pre-rendered in alphabetical order. Tho in the list they are put in the order I want to be pre-rendered from left to right. I couldn't find anything about that topic. Is there a way to set priority/order in which urls are being pre-rendered? Or is there a strong reason why it is made like that right now?

Example:

```
{
    "prerender": [
        {
            "source": "list",
            "urls": [
                "http://localhost:3000/ordinaryHref_03",
                "http://localhost:3000/ordinaryHref_02"
            ]
        }
    ]
}
```

![Screenshot 2023-11-22 at 16 16 33](https://github.com/WICG/nav-speculation/assets/326949/0edc6413-f7ef-4d6a-bdca-6c752d57fb8c)

~~Update: Okay if I get every url in separate speculation rule script tag then it works in the order that I want. Is that expected behavior? I tried going a little bit in the chromium code but I didn't see anything that is sorting the speculation rules in any specific order. Of course maybe I was just looking at the wrong place :D~~

**Comment by domenic** [comment]
As far as I can tell, this is not an issue with the specification we're developing in this repository, but instead a question about a specific implementation, the Chromium one. So, I'll close it, and encourage you to file an issue on https://crbug.com/ for future Chromium-specific problems.

I've done so for you at https://bugs.chromium.org/p/chromium/issues/detail?id=1505301 right now.

**Comment by thinklinux** [comment]
@domenic Thank you! You are awesome!
