### ISSUE TITLE
Recursive prerendering behaviour consideration

### ISSUE THREAD

**Issue by SulemanAhmadd** [WICG/nav-speculation#326]
It is unclear to me from the speculation rules specification on how recursive prerendering is taken care of i.e. when a prerendered page has speculation rules script to prerender further next set of pages.

Consider, Page A prerenders Page B. Now, Page B has speculation rules to prerender Page C with "immediate" eagerness. Will the prerendering of Page C from Page B be deferred, until Page B is activated? It would nice to briefly clarify child prerendering behaviour in the considerations section.

**Comment by domenic** [comment]
In the specification, this is allowed.

In the Chromium implementation, we defer prerendering for all non-rendered pages (including pages being prerendered), as part of the user agent's general discretion to not prerender when it believes doing so would not be a good use of the user's resources.

Hope this helps!
