### ISSUE TITLE
Prerendering and CSP

### ISSUE THREAD

**Issue by mfalken** [WICG/nav-speculation#43]
How should the CSP of a page affect a prerendered page that was triggered by that page?

One option is to say the CSP of the triggering page should propagate to the prerendered page, since the prerendered page is not something that will necessarily be navigated to, so it should still be subject to the constraints of the triggering page. However I feel that's problematic:

- The CSP can break the page in a way that's not reproducible when the page is navigated to normally without prerendering.
- When the page is activated, the CSP would presumably need to be change to become the normal CSP of the page.

Admittedly both of those arguments hold for any restrictions on prerendered content, so they may not be convincing. However, I'm tending to think that as its own browsing context, the prerendered page should be subject to only its own CSP and not the triggering page's. With that goal, here is a first cut at proposed behavior for relevant CSP directives:

### navigate-to

Background: CSP [navigate-to](https://w3c.github.io/webappsec-csp/#directive-navigate-to) restricts what URLs a document can initiate navigation to via <a>, window.location, etc. The CSP of the initiator document, not the target document, specifies the policy. From my reading of the spec, navigate-to applies to redirects of the navigation request too.

Proposal: This should behave mostly like a link click. Apply navigate-to checks to the prerender initial URL and to any redirects. For example, suppose a document has `navigate-to: a.test`, and it triggers a prerender to `a.test` which redirects to `b.test`. The document shouldn't be able to  later initiate a navigation to `a.test` which activates the prerendered page, resulting in a navigation to `b.test`. However, if the prerendered page does a client-side navigation from `a.test` to `b.test`, it would be fine for the document to initiate a navigation to `a.test` which activates the prerendered page, since this is the behavior I expect a link click to have under this CSP.

The easiest way to enforce this would be to cancel prerendering if the initial URL or any redirect violates `navigate-to`, and once the first response is committed let the prerendering page continue without constraints of the initiator page's CSP. (Otherwise, on activation, replay the redirect chain of prerendering and block the activation navigation if it would result in a violation of the directive.)

### connect-src

Background: CSP [connect-src](https://w3c.github.io/webappsec-csp/#directive-connect-src) restricts which requests a document can make by script.

Proposal: APIs that trigger prerendering will be constrained by this directive for the prerendering navigation request and its redirects. Subresource requests from the prerendered page will not be affected by the connect-src of the triggering document. Furthermore, once the prerendered page commits, any client-side navigation is not affected by connect-src.

### prefetch-src

Background: CSP [prefetch-src](https://w3c.github.io/webappsec-csp/#directive-prefetch-src) restricts which resources can be prefetched/prerendered from a document.

Proposal: Same as connect-src: it only acts on the main resource and not on the subresources of the prerendered page. 

What do people think? cc @domenic @jeremyroman @domfarolino

**Comment by jeremyroman** [comment]
I don't think it should be subject to the referrer's CSP. We don't constrain opened windows, subframes, etc. in that way. If a page isn't comfortable with that risk, it shouldn't prerender. We *might* want a distinct prerender-src from prefetch-src if this distinction frequently matters.

re. navigate-to, I'm surprised that it is enforced on HTTP redirects, but it does appear it is based on my reading too; I haven't checked in Chromium. (It presumably isn't enforced on client-side redirects, though.) Enforcing it on the redirect chain makes sense in light of that.

I don't really think connect-src is applicable, though -- prefetch-src seems more appropriate. connect-src is for things like WebSockets where you make a scripted connection to a server, other than things that go through normal fetch.

**Comment by domenic** [comment]
We thought a lot about this for portals. I think I ported this over to prerendering in https://github.com/jeremyroman/alternate-loading-modes/blob/main/browsing-context.md#csp-integration

**Comment by mfalken** [comment]
Thanks! I apologize for seeing the CSP integration section already exists.

Some comments:
- navigate-to: The section looks aligned with what I was thinking: the navigate-to directive of the triggering page applies to the prerendering navigation, which can be blocked accordingly. It may be good for the section to say something about server-side redirects. Right now it says "prohibit navigations based on the URL of the link clicked" which may sound like redirects are not restricted (assuming I'm reading the navigate-to spec correctly).
- connect-src:  @jeremyroman's comment is fair ... I suppose if `<link rel=prerender>` is not restricted by connect-src, it doesn't make sense for `speculationrules` to be. Makes sense.
- prefetch-src: The section doesn't make it clear whether it applies to the navigation request only or also to subresource requests from the prerendered page. Is the intention to only be on the navigation request? If so, I agree.

**Comment by domenic** [comment]
> prefetch-src: The section doesn't make it clear whether it applies to the navigation request only or also to subresource requests from the prerendered page. Is the intention to only be on the navigation request? If so, I agree.

Fair question. I guess only the navigation request really makes sense. If you're using CSP as a safelist, then you only want to bother safelisting the main resource; having to track down all the subresources would be a pain. If you're using CSP as a blocklist, then blocking the main resource should suffice, and it'd be potentially dangerous to allow the referring page to allow the main resource through but block some of its subresources.

I'll send a PR to make this clearer. Although eventually it needs to be specced... It looks like that'd be done by setting the request [initiator](https://fetch.spec.whatwg.org/#concept-request-initiator). /cc @domfarolino

**Comment by domenic** [comment]
> I'll send a PR to make this clearer.

I started working on a PR but now I'm unsure whether we should expand that section in prerendering browsing contexts, or move some or all of it to the fetch.md doc. Thoughts appreciated. Maybe it doesn't matter much since we had this discussion so we're all clear, and the most important next step is working on the spec.

**Comment by mfalken** [comment]
Thanks! For whether to move it, +1 to "it doesn't matter much" and working on the spec as the next important step.

**Comment by toyoshim** [comment]
Regarding `navigate-to`, can I assume Matt's understanding below is correct?
> Right now it says "prohibit navigations based on the URL of the link clicked" which may sound like redirects are not restricted (assuming I'm reading the navigate-to spec correctly).

**Comment by domenic** [comment]
@toyoshim in that sentence Matt is pointing out that the current explainer is not detailed enough and fails to deal with redirects. However, per his proposal (which I agree with), we should restrict redirects.

**Comment by toyoshim** [comment]
Thanks for clarification!

I also asked Mike West on chromium implementation status on CSP `navigate-to` and `prefetch-src`, and it turned out that `navigate-to` is still under development and won't be shipped soon. So probably Prerender2 won't support it in the initial implementation. On the other hand, `prefetch-src` will be shipped soon. So, I continue discussing `prefetc-src` support for Prerender2 with the team.

**Comment by mfalken** [comment]
In a review, @camillelamy [suggests]( https://docs.google.com/document/d/1P2VKCLpmnNm_cRAjUeE-bqLL0bslL_zKqiNeCzNom_w/edit?disco=AAAAMhlZwAE) that we check the CSP of the current page at activation-time as well, and avoid activating a prerendered page that is disallowed by the page's current CSP. The reasoning is that the page's CSP may have changed after the prerender started. This makes sense to me and I plan to implement it. Do others agree?

I wonder if we should also start taking this issue to the CSP repo.

**Comment by domenic** [comment]
I didn't realize that part of CSP could change after the page loads :(. Given that, indeed, it seems like the right path...

**Comment by mfalken** [comment]
Some cases we considered are:
- The `<script type=speculationrules>` appears before a `<meta>` element that disallows it.
- A `<meta>` that disallows an existing prerender is added after the prerender started.
- The document does something like `document.write()` which changes the document completely.

Looking at https://w3c.github.io/webappsec-csp/#meta-element, it says that "policies in meta elements are not applied to content which precedes them" which seems to mean according to spec we should allow a prerender to be triggered if the `<meta>` did not exist at the time of `<script type=speculationrules>`. I'm not sure what it means about whether we should cancel a prerender or refuse to activate it upon the CSP change?

I think I'll take this to the CSP repo for wider input.

**Comment by toyoshim** [comment]
NavigationRequest::CheckCSPDirectives takes two CSP, one is for parent frame and the other is for the initiator page.
And, here we apply the initiator page's CSP for all navigation during prerendering.

For the prerendering main frame, the initiator here meant the prerender triggering page apparently, and this is correct.
But for prerendering subframes, both parent's and initiator's point to the same parent's CSP. So, this would not be expected. We should apply prefetch-src only for the prerendering main frame.

Regarding the self-navigations, Chromium's Prerender2 disallow any main frame navigation during prerendering. So, it doesn't matter? But, it would not be nice if the check sends unexpected violation reports as CSP checks happen first before the navigation restriction handled in the throttles.

cc: @nhiroki

**Comment by noamr** [comment]
I believe that we should check `prefetch-src` and `navigate-to` when prerendering, and `navigate-to` again when activating (at which point exfiltration would have already happen). This is in line with preloading, where CSP is checked both at preload and consume time.

`navigate-to` is already checked (in the spec) when prerendering during `process a navigate fetch`.
