### ISSUE TITLE
Possible counterpoint for “Alternatives Considered”

### ISSUE THREAD

**Issue by taylor-hunt-kr** [WICG/nav-speculation#66]
> `<link>` also doesn't lend itself to reducing duplication with anchors alread in the document, requiring the author to either statically insert the full set of links into the document resource (and since they appear in the `<head>`, this implies buffering) or dynamically synchronize the links in the page with `<link>` references in the head, potentially updating them as script mutates the document.

To me, this seems to ask the question “why not `<a rel=prerender-with-resources>`?” I’m sure there _are_ reasons not to, like how `<a rel=prefetch>` was not adopted by browsers, but I would be very interested in seeing it addressed.

**Comment by jeremyroman** [comment]
I don't recall this option being proposed at the time this was written.

I think the other reasons do continue to apply, like having somewhere convenient to fit additional metadata (one of the cases we're interested in is requiring client IP anonymization, for instance) and allowing the possibility of bulk rules that could be added in one place (though this is to some extent achievable with script).

I'm happy to revise this text to address this once I'm sure I understand your thoughts better.
