### ISSUE TITLE
Web Auth API and WebOTP API restrictions

### ISSUE THREAD

**Issue by toyoshim** [WICG/nav-speculation#80]
We want a WebOTP API section in 7.3 as
Add DelayWhielPrerendering to navigation.credentials.get()

**Comment by mfalken** [comment]
By the way there is already a WPT prepared for this at https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/wpt_internal/prerender/restriction-web-auth.https.html (if you haven't seen it)

**Comment by noamr** [comment]
Should be fixed in https://github.com/WICG/nav-speculation/pull/110

**Comment by jeremyroman** [comment]
@noamr Was this indeed fixed in #110? If so, can we close this?

**Comment by noamr** [comment]
> @noamr Was this indeed fixed in #110? If so, can we close this?

Indeed
