### ISSUE TITLE
Can we make https://jeremyroman.github.io/alternate-loading-modes/ redirect to the new link?

### ISSUE THREAD

**Issue by rakina** [WICG/nav-speculation#88]
Hi, just realized the old repo got moved to WICG, and it looks like https://github.com/jeremyroman/alternate-loading-modes/ redirects to this repo now which is great. However there are a few links that point to the old draft spec  (https://jeremyroman.github.io/alternate-loading-modes/) like the one in [W3C Design Principles doc](https://w3ctag.github.io/design-principles/#gate-fully-active) and even the link in [this repo's README.md](https://github.com/WICG/nav-speculation#prerendering-revamped).

Is it possible to make the old draft spec link redirect to the new draft spec?
If not that's fine, I'll send a PR to update the one in the Design Principles doc

(cc @jeremyroman)

**Comment by jeremyroman** [comment]
I'd hoped this would be automatic but since it's apparently not, I'll see what I can do about putting up a stub repo that redirects.

**Comment by domenic** [comment]
https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7 documents the trick for doing such a redirect.

**Comment by jeremyroman** [comment]
Done.

**Comment by jeremyroman** [comment]
https://github.com/jeremyroman/jeremyroman.github.io/commit/d81087bc8c81b1e93fae5d607d737d1ca2882bac

**Comment by rakina** [comment]
Thanks a lot! The prerendering people and I will probably update the existing links where it's easy to do so too!
