### ISSUE TITLE
Cross-origin prerendering popularity contests

### ISSUE THREAD

**Issue by rhiaro** [WICG/nav-speculation#92]
A couple of thoughts about how prerendering sites could artificially influence peoples' desire to visit particular sites.

A UA heuristic could be that popular sites get prerendered more frequently, and thus appear faster to load to the visitor, so more desirable to visit, therefore prerendered sites become more popular, creating a cycle where - so to speak - the rich get richer and the poor get poorer. This may lead to a concentration of power around a particular group of sites in any given sector.

Could a site which links to many third parties subtly favour certain sites over others by recommending to the UA to prerender them? Imagine a comparison site, which links out to several sites providing similar services. Except one of the service providers is a subsidiary of the same company that runs the comparison site. The visitor may perceive that result as better if it is faster to load, on account of it having been prerendered, and be inclined more favourably towards accessing services there as a result.

Will the UAs heuristics for prerendering *always* be based on things directly related to the site visitor (I've seen mention of mouse position, etc) or will there be out of band factors? Can, for example, a UA decide never to prerender a site that it has deemed inappropriate for some reason or, perhaps, is the website of a competing UA? Can companies pay a UA to more frequently prerender their sites over their competitors? I could see these sorts of things being mitigated by some normative work around what the actual heuristics might be, rather than leaving them as a completely opaque box in the UA implementation.

**Comment by KenjiBaheux** [comment]
Thanks for the feedback.
See the 2 separate issues for our assessment.
