### ISSUE TITLE
Prefetching and Cross-Origin-Opener-Policy

### ISSUE THREAD

**Issue by jeremyroman** [WICG/nav-speculation#95]
https://wicg.github.io/nav-speculation/prefetch.html has an inline issue to deal with `Cross-Origin-Opener-Policy`.

Briefly, I notice a few things that happen with COOP during navigation in a top-level browsing context:
* on each redirect, the whole process can fail if sandbox flags are set but the policy is not `unsafe-none`
* on each redirect, if a BCG switch appears to be necessary and the BCG has another top-level browsing context, report a violation
* on the final response, the BCG switch occurs if necessary, based on an accumulated COOP enforcement result

Since reporting violations purely for prefetched navigations seems noisy, and in any case the extra BCG issue may have gone away by the time the navigation actually occurs, it seems most natural to defer all but the first of these to the actual navigation. It seems that this will require holding onto the responses all along the redirect chain in order to be able to perform COOP checks and potentially report violations on all of them, at the time the prefetched navigation is used.

Does that seem like the right approach? @domenic @camillelamy

**Comment by camillelamy** [comment]
That seems reasonable. Note that @hemeryar is changing the first one (see discussion in [this issue](https://github.com/whatwg/html/issues/7345)).

**Comment by domenic** [comment]
Sounds good to me too.
